services:
  - type: web
    name: query-engine-backend
    env: docker
    dockerfilePath: Dockerfile
    rootDir: backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
